version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EXPO_PUBLIC_API_BASE_URL=https://api.moa-app.com # 실제 배포 시 연동할 NCP 백엔드 도메인 주소로 수정
    container_name: moa-expo-web
    restart: always
    ports:
      - "80:80"
