server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html; # Expo Router 등 클라이언트 라우팅 404 방지
    }

    # 정적 리소스 캐싱 정책
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|json)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
