"""initial schema 13 tables

Revision ID: 20751b93fd22
Revises: 
Create Date: 2026-06-18 05:30:50.085233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20751b93fd22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('senior_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('guardian',
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('fcm_token', sa.String(length=255), nullable=True),
    sa.Column('biometric_consent_yn', sa.Boolean(), nullable=False),
    sa.Column('consent_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("gender IN ('M', 'F')", name='ck_guardian_gender'),
    sa.PrimaryKeyConstraint('guardian_id')
    )
    op.create_index(op.f('ix_guardian_email'), 'guardian', ['email'], unique=True)
    op.create_table('script',
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('script_id')
    )
    op.create_table('senior',
    sa.Column('senior_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('fcm_token', sa.String(length=255), nullable=True),
    sa.Column('smoking_yn', sa.Boolean(), nullable=True),
    sa.Column('bmi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('medical_history', sa.String(), nullable=True),
    sa.Column('biometric_consent_yn', sa.Boolean(), nullable=False),
    sa.Column('consent_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("gender IN ('M', 'F')", name='ck_senior_gender'),
    sa.PrimaryKeyConstraint('senior_id')
    )
    op.create_index(op.f('ix_senior_email'), 'senior', ['email'], unique=True)
    op.create_table('guardian_senior',
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('senior_id', sa.UUID(), nullable=False),
    sa.Column('link_status', sa.String(length=10), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("link_status IN ('PENDING','ACTIVE','REVOKED')", name='ck_guardian_senior_status'),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.guardian_id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['senior.senior_id'], ),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('guardian_id', 'senior_id', name='uq_guardian_senior')
    )
    op.create_table('invite',
    sa.Column('token', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.guardian_id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('medication',
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('senior_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('medicine_name', sa.String(length=100), nullable=False),
    sa.Column('intake_time', sa.Time(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.guardian_id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['senior.senior_id'], ),
    sa.PrimaryKeyConstraint('medication_id')
    )
    op.create_table('monthly_report',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('senior_id', sa.UUID(), nullable=False),
    sa.Column('report_month', sa.String(length=7), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['senior.senior_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('senior_id', 'report_month', name='uq_monthly_report_senior_month')
    )
    op.create_table('risk_prediction',
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('senior_id', sa.UUID(), nullable=False),
    sa.Column('parkinson_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('dementia_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('depression_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('diabetes_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('parkinson_level', sa.String(length=10), nullable=False),
    sa.Column('dementia_level', sa.String(length=10), nullable=False),
    sa.Column('depression_level', sa.String(length=10), nullable=False),
    sa.Column('diabetes_level', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("dementia_level IN ('GREEN','YELLOW','AMBER')", name='ck_risk_dementia_level'),
    sa.CheckConstraint("depression_level IN ('GREEN','YELLOW','AMBER')", name='ck_risk_depression_level'),
    sa.CheckConstraint("diabetes_level IN ('GREEN','YELLOW','AMBER')", name='ck_risk_diabetes_level'),
    sa.CheckConstraint("parkinson_level IN ('GREEN','YELLOW','AMBER')", name='ck_risk_parkinson_level'),
    sa.CheckConstraint('dementia_score BETWEEN 0 AND 1', name='ck_risk_dementia_score'),
    sa.CheckConstraint('depression_score BETWEEN 0 AND 1', name='ck_risk_depression_score'),
    sa.CheckConstraint('diabetes_score BETWEEN 0 AND 1', name='ck_risk_diabetes_score'),
    sa.CheckConstraint('parkinson_score BETWEEN 0 AND 1', name='ck_risk_parkinson_score'),
    sa.ForeignKeyConstraint(['senior_id'], ['senior.senior_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_table('script_record',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('senior_id', sa.UUID(), nullable=False),
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['script.script_id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['senior.senior_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('voice_feature',
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('senior_id', sa.UUID(), nullable=False),
    sa.Column('collect_type', sa.String(length=10), nullable=False),
    sa.Column('voice_features', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("collect_type IN ('SCRIPT','CHATBOT')", name='ck_voice_feature_collect_type'),
    sa.ForeignKeyConstraint(['senior_id'], ['senior.senior_id'], ),
    sa.PrimaryKeyConstraint('feature_id')
    )
    op.create_table('medication_check',
    sa.Column('check_id', sa.UUID(), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('senior_id', sa.UUID(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medication.medication_id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['senior.senior_id'], ),
    sa.PrimaryKeyConstraint('check_id'),
    sa.UniqueConstraint('medication_id', 'check_date', name='uq_medication_check_date')
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('senior_id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=True),
    sa.Column('medication_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("notification_type IN ('RISK','MEDICATION','HOSPITAL','INACTIVE')", name='ck_notification_type'),
    sa.CheckConstraint("status IN ('SENT','FAILED','READ')", name='ck_notification_status'),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.guardian_id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medication.medication_id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['risk_prediction.prediction_id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['senior.senior_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('medication_check')
    op.drop_table('voice_feature')
    op.drop_table('script_record')
    op.drop_table('risk_prediction')
    op.drop_table('monthly_report')
    op.drop_table('medication')
    op.drop_table('invite')
    op.drop_table('guardian_senior')
    op.drop_index(op.f('ix_senior_email'), table_name='senior')
    op.drop_table('senior')
    op.drop_table('script')
    op.drop_index(op.f('ix_guardian_email'), table_name='guardian')
    op.drop_table('guardian')
    op.drop_table('chat_session')
    # ### end Alembic commands ###
