"""add_hospital_visit

Revision ID: 355d7f58b24e
Revises: e6f7a8b9c0d1
Create Date: 2026-06-24 11:35:13.198897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '355d7f58b24e'
down_revision: Union[str, Sequence[str], None] = 'e6f7a8b9c0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_visit',
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('senior_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('hospital_name', sa.String(length=100), nullable=False),
    sa.Column('visit_datetime', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.guardian_id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['senior.senior_id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    op.alter_column('invite', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invite', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('notification', sa.Column('visit_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'notification', 'hospital_visit', ['visit_id'], ['visit_id'])
    op.alter_column('reconnect_code', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('reconnect_code', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_foreign_key(None, 'risk_prediction', 'senior', ['senior_id'], ['senior_id'])
    op.create_foreign_key(None, 'script_record', 'senior', ['senior_id'], ['senior_id'])
    op.alter_column('urgent_alert', 'alert_id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('urgent_alert', 'alert_status',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('urgent_alert', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_foreign_key(None, 'voice_feature', 'senior', ['senior_id'], ['senior_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voice_feature', type_='foreignkey')
    op.alter_column('urgent_alert', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('urgent_alert', 'alert_status',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('urgent_alert', 'alert_id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(None, 'script_record', type_='foreignkey')
    op.drop_constraint(None, 'risk_prediction', type_='foreignkey')
    op.alter_column('reconnect_code', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('reconnect_code', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'visit_id')
    op.alter_column('invite', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('invite', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_table('hospital_visit')
    # ### end Alembic commands ###
