"""add_hospital_visit_and_notif_settings

Revision ID: d7c21f38a71a
Revises: 6231a82bf1ee
Create Date: 2026-06-26 08:46:42.011190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7c21f38a71a'
down_revision: Union[str, Sequence[str], None] = '6231a82bf1ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('family_group', 'family_group_id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('family_group', 'status',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('family_group', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=1),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('family_group', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=1),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.add_column('guardian', sa.Column('push_enabled', sa.Boolean(), nullable=True))
    op.add_column('guardian', sa.Column('medication_push_enabled', sa.Boolean(), nullable=True))
    op.add_column('guardian', sa.Column('hospital_push_enabled', sa.Boolean(), nullable=True))
    op.execute("UPDATE guardian SET push_enabled = TRUE, medication_push_enabled = TRUE, hospital_push_enabled = TRUE")
    op.alter_column('guardian', 'push_enabled', nullable=False)
    op.alter_column('guardian', 'medication_push_enabled', nullable=False)
    op.alter_column('guardian', 'hospital_push_enabled', nullable=False)
    op.drop_column('guardian', 'notification_enabled')
    op.alter_column('guardian_member', 'guardian_member_id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('guardian_member', 'status',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('guardian_member', 'invite_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=1),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('guardian_member', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=1),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('guardian_member', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=1),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.add_column('hospital_visit', sa.Column('visit_date', sa.Date(), nullable=False))
    op.add_column('hospital_visit', sa.Column('visit_time', sa.Time(), nullable=False))
    op.add_column('hospital_visit', sa.Column('memo', sa.String(length=500), nullable=True))
    op.drop_column('hospital_visit', 'visit_datetime')
    op.alter_column('medication', 'guardian_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('medication_reminder', 'status',
               existing_type=sa.VARCHAR(length=24),
               server_default=None,
               existing_nullable=False)
    op.alter_column('medication_reminder', 'reminder_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('medication_reminder', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=1),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_medication_reminder_retry'), table_name='medication_reminder')
    op.drop_index(op.f('ix_medication_reminder_senior_scheduled'), table_name='medication_reminder')
    op.drop_constraint(op.f('medication_reminder_senior_id_fkey'), 'medication_reminder', type_='foreignkey')
    op.drop_constraint(op.f('medication_reminder_medication_id_fkey'), 'medication_reminder', type_='foreignkey')
    op.create_foreign_key(None, 'medication_reminder', 'senior', ['senior_id'], ['senior_id'])
    op.create_foreign_key(None, 'medication_reminder', 'medication', ['medication_id'], ['medication_id'])
    op.add_column('notification', sa.Column('hospital_visit_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('notification_visit_id_fkey'), 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'hospital_visit', ['hospital_visit_id'], ['visit_id'])
    op.drop_column('notification', 'visit_id')
    op.add_column('senior', sa.Column('push_enabled', sa.Boolean(), nullable=True))
    op.add_column('senior', sa.Column('medication_push_enabled', sa.Boolean(), nullable=True))
    op.add_column('senior', sa.Column('hospital_push_enabled', sa.Boolean(), nullable=True))
    op.execute("UPDATE senior SET push_enabled = TRUE, medication_push_enabled = TRUE, hospital_push_enabled = TRUE")
    op.alter_column('senior', 'push_enabled', nullable=False)
    op.alter_column('senior', 'medication_push_enabled', nullable=False)
    op.alter_column('senior', 'hospital_push_enabled', nullable=False)
    op.drop_column('senior', 'notification_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('senior', sa.Column('notification_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('senior', 'hospital_push_enabled')
    op.drop_column('senior', 'medication_push_enabled')
    op.drop_column('senior', 'push_enabled')
    op.add_column('notification', sa.Column('visit_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key(op.f('notification_visit_id_fkey'), 'notification', 'hospital_visit', ['visit_id'], ['visit_id'])
    op.drop_column('notification', 'hospital_visit_id')
    op.drop_constraint(None, 'medication_reminder', type_='foreignkey')
    op.drop_constraint(None, 'medication_reminder', type_='foreignkey')
    op.create_foreign_key(op.f('medication_reminder_medication_id_fkey'), 'medication_reminder', 'medication', ['medication_id'], ['medication_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('medication_reminder_senior_id_fkey'), 'medication_reminder', 'senior', ['senior_id'], ['senior_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_medication_reminder_senior_scheduled'), 'medication_reminder', ['senior_id', 'scheduled_for'], unique=False)
    op.create_index(op.f('ix_medication_reminder_retry'), 'medication_reminder', ['status', 'retry_at'], unique=False)
    op.alter_column('medication_reminder', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=1),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('medication_reminder', 'reminder_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('medication_reminder', 'status',
               existing_type=sa.VARCHAR(length=24),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=False)
    op.alter_column('medication', 'guardian_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('hospital_visit', sa.Column('visit_datetime', postgresql.TIMESTAMP(precision=1), autoincrement=False, nullable=False))
    op.drop_column('hospital_visit', 'memo')
    op.drop_column('hospital_visit', 'visit_time')
    op.drop_column('hospital_visit', 'visit_date')
    op.alter_column('guardian_member', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True, precision=1),
               existing_nullable=False)
    op.alter_column('guardian_member', 'joined_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True, precision=1),
               existing_nullable=True)
    op.alter_column('guardian_member', 'invite_expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True, precision=1),
               existing_nullable=True)
    op.alter_column('guardian_member', 'status',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=False)
    op.alter_column('guardian_member', 'guardian_member_id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.add_column('guardian', sa.Column('notification_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('guardian', 'hospital_push_enabled')
    op.drop_column('guardian', 'medication_push_enabled')
    op.drop_column('guardian', 'push_enabled')
    op.alter_column('family_group', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True, precision=1),
               existing_nullable=False)
    op.alter_column('family_group', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True, precision=1),
               existing_nullable=False)
    op.alter_column('family_group', 'status',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'ACTIVE'::character varying"),
               existing_nullable=False)
    op.alter_column('family_group', 'family_group_id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
