import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useRouter } from "expo-router";
import { Bell, Hospital, Mic, Pill } from "lucide-react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { LinearGradient } from "expo-linear-gradient";
import { useMedicationStore } from "../stores/medicationStore";

export default function NotificationCenterPage() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const medications = useMedicationStore((s) => s.medications); const schedules = useMedicationStore((s) => s.hospitalSchedules);
  const hospital = schedules.find((schedule) => schedule.enabled);
  return <View style={[styles.fill,{paddingTop:insets.top}]}><LinearGradient colors={["#F7D6AC","#FFF2DE","#F7D6AC"]} style={StyleSheet.absoluteFill}/><View style={styles.header}><Bell size={29} color="#3B2318"/><Text style={styles.title}>알림센터</Text></View><ScrollView contentContainerStyle={[styles.list,{paddingBottom:insets.bottom+28}]}><Text style={styles.subtitle}>오늘 확인해야 할 알림이에요</Text>{medications.map(m=><TouchableOpacity key={m.id} style={styles.card} onPress={()=>router.push({pathname:"/(elder)/health",params:{section:"medication"}})}><View style={[styles.icon,styles.pending]}><Pill color="#D4783B" size={25}/></View><View style={styles.cardBody}><Text style={styles.cardTitle}>{m.medicineName} · 복약 안내</Text><Text style={styles.cardSub}>{m.scheduledTime} · 복약/병원 화면에서 확인해요</Text></View></TouchableOpacity>)}{hospital&&<TouchableOpacity style={styles.card} onPress={()=>router.push({pathname:"/(elder)/hospital-form",params:{id:hospital.id}})}><View style={[styles.icon,styles.hospital]}><Hospital color="#7B6AB0" size={24}/></View><View style={styles.cardBody}><Text style={styles.cardTitle}>병원 방문까지 3일 남았어요</Text><Text style={styles.cardSub}>{hospital.hospitalName} · 일정을 확인해요</Text></View></TouchableOpacity>}<TouchableOpacity style={styles.card} onPress={()=>router.replace("/(elder)")}><View style={[styles.icon,styles.voice]}><Mic color="#3B7895" size={24}/></View><View style={styles.cardBody}><Text style={styles.cardTitle}>오늘 음성 검사 미완료</Text><Text style={styles.cardSub}>지금 목소리 검사로 건강을 확인해요</Text></View></TouchableOpacity></ScrollView></View>;
}
const styles=StyleSheet.create({fill:{flex:1},header:{flexDirection:"row",alignItems:"center",gap:10,paddingHorizontal:24,paddingVertical:22},title:{fontSize:30,fontWeight:"900",color:"#3B2318"},list:{padding:20,gap:12},subtitle:{fontSize:18,fontWeight:"900",color:"#765E52",marginBottom:2},card:{minHeight:92,borderRadius:20,backgroundColor:"rgba(255,255,255,0.88)",padding:16,flexDirection:"row",alignItems:"center",gap:13,borderWidth:1,borderColor:"rgba(117,76,42,0.10)"},icon:{width:50,height:50,borderRadius:17,alignItems:"center",justifyContent:"center"},pending:{backgroundColor:"#FFF0D9"},hospital:{backgroundColor:"#EEE9FA"},voice:{backgroundColor:"#E0F0F5"},cardBody:{flex:1,gap:5},cardTitle:{fontSize:18,fontWeight:"900",color:"#3B2318"},cardSub:{fontSize:14,fontWeight:"600",color:"#765E52"}});
